name: Publish
run-name: Publish to Modrinth by @${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # needed for versioning
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: "${{ runner.os }}-bluemapsignmarkers-${{ hashFiles('**/*.gradle*') }}"
          restore-keys: |
            ${{ runner.os }}-bluemapsignmarkers-
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Publish alpha to Modrinth
        if: startsWith(github.ref, 'refs/heads/')
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew modrinth -PbuildNumber=${{ github.run_number }}
      - name: Publish release to Modrinth
        if: startsWith(github.ref, 'refs/tags/')
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew modrinth -PbuildNumber=${{ github.run_number }} -PisRelease
